### PR TITLE
Feature/#3 red cap

### PR DESCRIPTION
**Pull request by theendsofinvention**
Red CAP is ready for testing.

Latest testing artifact is [0.1.0.64](https://ci.appveyor.com/api/buildjobs/871o66spgwg30b2c/artifacts/SDCM_0.1.0.64.miz).

I've made a few changes, all documented in the commits and in the script.

Markdown formatted help intended for the pilots is available [here](https://github.com/132nd-vWing/SDCM/blob/feature/%233_red-cap/l10n/DEFAULT/CAP.md).

@132nd-Entropy @132ndNeck please do **NOT** push on develop until this is either discarded or approved, otherwise conflict merging will be a nightmare and I'll have to start the integration over; if there easily fixed bugs in this branch, I'd rather have it merged into develop and fix them later on.

### CODE REVIEW

**Comment by 132ndNeck** [comment]
@132nd-etcher I may have overlooked this and pushed  version to develop yesterday (it was some edits for the last time we ran the SDCM).

Any idea what I should do before accepting this feature?

(I am sorry for my long abscence here in github and missiondesign, but been very busy with work)

**Comment by theendsofinvention** [comment]
I have linked the latest build in my previous comment.

Before accepting the changes, you should review the mechanisms I've implemented and let me know of any changes you'd like.

I will integrate your latest develop changes manually later.

**Comment by 132nd-Entropy** [comment]
I tested it and am super happy with the result!! Very well done Etcher, everything 
works perfectly!! 
One very minor thing:
Once a plane goes RTB, the counter should be reduced by 1, right now, the script gives you '2 CAP active' when 1 is RTBing and its replacement is in the air. 
very minor issue, that is not important now, I suggest to push your version of the script asap since its going to be a HUUUGE addon for the combat mission. Well done!!!

**Comment by theendsofinvention** [comment]
The counter shows the replacement as active because it's already active as a CAP, and able to engage.

If send places home without a replacement, the counter should decrease accordingly.

**Comment by 132nd-Entropy** [comment]
yes, the new plane should be increasing the counter, but the old plane, on its way home, wont engage anyone, therefore the counter for the RTBing plane should be decreased on RTB, not on despawn (but again, its just a minor point and should, imo, not delay the implementation of the CAP script

**Pull request merged**
